export type MockUser = {
	id: string;
	name: string;
	email: string;
	role: "admin" | "manager" | "user" | "viewer";
	status: "active" | "inactive" | "pending" | "banned";
	banned: boolean;
	department: "engineering" | "design" | "marketing" | "sales" | "hr";
	age: number;
	createdAt: Date;
	avatarUrl: string | null;
};

export const MOCK_USERS: MockUser[] = [
	{
		id: "user-01",
		name: "Ana Paula Souza",
		email: "ana.paula.souza@empresa.com.br",
		role: "admin",
		status: "active",
		banned: false,
		department: "engineering",
		age: 29,
		createdAt: new Date("2024-01-12T09:15:00.000Z"),
		avatarUrl: "https://i.pravatar.cc/40?u=user-01",
	},
	{
		id: "user-02",
		name: "João Pedro Lima",
		email: "joao.pedro.lima@empresa.com.br",
		role: "manager",
		status: "inactive",
		banned: false,
		department: "sales",
		age: 41,
		createdAt: new Date("2024-02-18T11:30:00.000Z"),
		avatarUrl: null,
	},
	{
		id: "user-03",
		name: "Mariana Alves",
		email: "mariana.alves@empresa.com.br",
		role: "user",
		status: "pending",
		banned: false,
		department: "design",
		age: 24,
		createdAt: new Date("2024-03-05T14:45:00.000Z"),
		avatarUrl: "https://i.pravatar.cc/40?u=user-03",
	},
	{
		id: "user-04",
		name: "Lucas Ferreira",
		email: "lucas.ferreira@empresa.com.br",
		role: "viewer",
		status: "banned",
		banned: true,
		department: "marketing",
		age: 33,
		createdAt: new Date("2024-04-22T08:20:00.000Z"),
		avatarUrl: null,
	},
	{
		id: "user-05",
		name: "Beatriz Costa",
		email: "beatriz.costa@empresa.com.br",
		role: "admin",
		status: "active",
		banned: false,
		department: "hr",
		age: 38,
		createdAt: new Date("2024-05-14T13:10:00.000Z"),
		avatarUrl: "https://i.pravatar.cc/40?u=user-05",
	},
	{
		id: "user-06",
		name: "Rafael Gomes",
		email: "rafael.gomes@empresa.com.br",
		role: "manager",
		status: "inactive",
		banned: false,
		department: "engineering",
		age: 45,
		createdAt: new Date("2024-06-03T16:05:00.000Z"),
		avatarUrl: "https://i.pravatar.cc/40?u=user-06",
	},
	{
		id: "user-07",
		name: "Camila Rocha",
		email: "camila.rocha@empresa.com.br",
		role: "user",
		status: "pending",
		banned: false,
		department: "marketing",
		age: 27,
		createdAt: new Date("2024-07-21T10:40:00.000Z"),
		avatarUrl: null,
	},
	{
		id: "user-08",
		name: "Thiago Martins",
		email: "thiago.martins@empresa.com.br",
		role: "viewer",
		status: "banned",
		banned: true,
		department: "sales",
		age: 52,
		createdAt: new Date("2024-08-09T12:00:00.000Z"),
		avatarUrl: "https://i.pravatar.cc/40?u=user-08",
	},
	{
		id: "user-09",
		name: "Juliana Ribeiro",
		email: "juliana.ribeiro@empresa.com.br",
		role: "admin",
		status: "active",
		banned: false,
		department: "design",
		age: 31,
		createdAt: new Date("2024-09-17T09:55:00.000Z"),
		avatarUrl: null,
	},
	{
		id: "user-10",
		name: "Felipe Nascimento",
		email: "felipe.nascimento@empresa.com.br",
		role: "manager",
		status: "inactive",
		banned: false,
		department: "marketing",
		age: 36,
		createdAt: new Date("2024-10-28T15:25:00.000Z"),
		avatarUrl: "https://i.pravatar.cc/40?u=user-10",
	},
	{
		id: "user-11",
		name: "Larissa Mendes",
		email: "larissa.mendes@empresa.com.br",
		role: "user",
		status: "pending",
		banned: false,
		department: "hr",
		age: 22,
		createdAt: new Date("2024-11-11T18:15:00.000Z"),
		avatarUrl: null,
	},
	{
		id: "user-12",
		name: "Bruno Teixeira",
		email: "bruno.teixeira@empresa.com.br",
		role: "viewer",
		status: "banned",
		banned: true,
		department: "engineering",
		age: 47,
		createdAt: new Date("2024-12-07T07:45:00.000Z"),
		avatarUrl: "https://i.pravatar.cc/40?u=user-12",
	},
	{
		id: "user-13",
		name: "Patrícia Azevedo",
		email: "patricia.azevedo@empresa.com.br",
		role: "admin",
		status: "active",
		banned: false,
		department: "sales",
		age: 55,
		createdAt: new Date("2025-01-16T08:35:00.000Z"),
		avatarUrl: "https://i.pravatar.cc/40?u=user-13",
	},
	{
		id: "user-14",
		name: "Gabriel Barros",
		email: "gabriel.barros@empresa.com.br",
		role: "manager",
		status: "inactive",
		banned: false,
		department: "design",
		age: 28,
		createdAt: new Date("2025-02-24T13:05:00.000Z"),
		avatarUrl: null,
	},
	{
		id: "user-15",
		name: "Fernanda Dias",
		email: "fernanda.dias@empresa.com.br",
		role: "user",
		status: "pending",
		banned: false,
		department: "marketing",
		age: 34,
		createdAt: new Date("2025-03-19T17:20:00.000Z"),
		avatarUrl: "https://i.pravatar.cc/40?u=user-15",
	},
	{
		id: "user-16",
		name: "Rodrigo Pires",
		email: "rodrigo.pires@empresa.com.br",
		role: "viewer",
		status: "banned",
		banned: true,
		department: "hr",
		age: 26,
		createdAt: new Date("2025-04-07T06:50:00.000Z"),
		avatarUrl: null,
	},
	{
		id: "user-17",
		name: "Aline Batista",
		email: "aline.batista@empresa.com.br",
		role: "admin",
		status: "active",
		banned: false,
		department: "engineering",
		age: 42,
		createdAt: new Date("2025-05-23T09:10:00.000Z"),
		avatarUrl: "https://i.pravatar.cc/40?u=user-17",
	},
	{
		id: "user-18",
		name: "Carlos Henrique Santos",
		email: "carlos.henrique.santos@empresa.com.br",
		role: "manager",
		status: "inactive",
		banned: false,
		department: "sales",
		age: 58,
		createdAt: new Date("2025-06-11T14:30:00.000Z"),
		avatarUrl: null,
	},
	{
		id: "user-19",
		name: "Daniela Freitas",
		email: "daniela.freitas@empresa.com.br",
		role: "user",
		status: "pending",
		banned: false,
		department: "design",
		age: 21,
		createdAt: new Date("2025-07-29T11:25:00.000Z"),
		avatarUrl: "https://i.pravatar.cc/40?u=user-19",
	},
	{
		id: "user-20",
		name: "Eduardo Campos",
		email: "eduardo.campos@empresa.com.br",
		role: "viewer",
		status: "banned",
		banned: true,
		department: "marketing",
		age: 40,
		createdAt: new Date("2025-08-15T16:40:00.000Z"),
		avatarUrl: null,
	},
	{
		id: "user-21",
		name: "Isabela Monteiro",
		email: "isabela.monteiro@empresa.com.br",
		role: "admin",
		status: "active",
		banned: false,
		department: "hr",
		age: 37,
		createdAt: new Date("2025-09-03T10:00:00.000Z"),
		avatarUrl: "https://i.pravatar.cc/40?u=user-21",
	},
	{
		id: "user-22",
		name: "Matheus Vieira",
		email: "matheus.vieira@empresa.com.br",
		role: "manager",
		status: "inactive",
		banned: false,
		department: "engineering",
		age: 30,
		createdAt: new Date("2025-10-26T08:15:00.000Z"),
		avatarUrl: null,
	},
	{
		id: "user-23",
		name: "Renata Pimenta",
		email: "renata.pimenta@empresa.com.br",
		role: "user",
		status: "pending",
		banned: false,
		department: "sales",
		age: 44,
		createdAt: new Date("2025-11-18T19:05:00.000Z"),
		avatarUrl: "https://i.pravatar.cc/40?u=user-23",
	},
	{
		id: "user-24",
		name: "Vinícius Cardoso",
		email: "vinicius.cardoso@empresa.com.br",
		role: "viewer",
		status: "banned",
		banned: true,
		department: "design",
		age: 23,
		createdAt: new Date("2025-12-09T12:50:00.000Z"),
		avatarUrl: null,
	},
	{
		id: "user-25",
		name: "Priscila Barbosa",
		email: "priscila.barbosa@empresa.com.br",
		role: "admin",
		status: "active",
		banned: false,
		department: "marketing",
		age: 46,
		createdAt: new Date("2026-01-14T07:30:00.000Z"),
		avatarUrl: "https://i.pravatar.cc/40?u=user-25",
	},
	{
		id: "user-26",
		name: "Henrique Moura",
		email: "henrique.moura@empresa.com.br",
		role: "manager",
		status: "inactive",
		banned: false,
		department: "hr",
		age: 53,
		createdAt: new Date("2026-02-22T15:10:00.000Z"),
		avatarUrl: null,
	},
	{
		id: "user-27",
		name: "Sofia Correia",
		email: "sofia.correia@empresa.com.br",
		role: "user",
		status: "pending",
		banned: false,
		department: "engineering",
		age: 25,
		createdAt: new Date("2026-03-08T09:45:00.000Z"),
		avatarUrl: "https://i.pravatar.cc/40?u=user-27",
	},
	{
		id: "user-28",
		name: "André Melo",
		email: "andre.melo@empresa.com.br",
		role: "viewer",
		status: "banned",
		banned: true,
		department: "sales",
		age: 35,
		createdAt: new Date("2026-04-17T11:00:00.000Z"),
		avatarUrl: null,
	},
	{
		id: "user-29",
		name: "Tatiane Oliveira",
		email: "tatiane.oliveira@empresa.com.br",
		role: "admin",
		status: "active",
		banned: false,
		department: "design",
		age: 32,
		createdAt: new Date("2026-05-12T14:55:00.000Z"),
		avatarUrl: "https://i.pravatar.cc/40?u=user-29",
	},
	{
		id: "user-30",
		name: "Everton Cardoso",
		email: "everton.cardoso@empresa.com.br",
		role: "manager",
		status: "inactive",
		banned: false,
		department: "marketing",
		age: 50,
		createdAt: new Date("2026-06-01T17:35:00.000Z"),
		avatarUrl: null,
	},
];
